service: article-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.env*'
    - '!tests/**'
    - '!.serverless/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!*.db'

functions:
  api:
    handler: main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
    environment:
      PYTHONPATH: /var/task
    timeout: 30
    memorySize: 256

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies for article API
    noDeploy:
      - sqlite3  # Already included in Lambda runtime