service: personal-portfolio-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true