AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Article API Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        STAGE: !Ref Stage
        PYTHONPATH: /var/task

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  TokenAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.authorizer.handler
      Runtime: python3.9

  ArticleApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main.handler
      Runtime: python3.9
      Events:
        ReadArticles:
          Type: Api
          Properties:
            Path: /articles
            Method: GET
            Auth:
              Authorizer: TokenAuthorizer
        ReadArticle:
          Type: Api
          Properties:
            Path: /articles/{proxy+}
            Method: GET
            Auth:
              Authorizer: TokenAuthorizer
        WriteArticles:
          Type: Api
          Properties:
            Path: /articles
            Method: POST
            Auth:
              Authorizer: TokenAuthorizer
        UpdateArticles:
          Type: Api
          Properties:
            Path: /articles/{proxy+}
            Method: PUT
            Auth:
              Authorizer: TokenAuthorizer
        DeleteArticles:
          Type: Api
          Properties:
            Path: /articles/{proxy+}
            Method: DELETE
            Auth:
              Authorizer: TokenAuthorizer
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          STAGE: !Ref Stage

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}" 